<?php /* Custom module created by giaidieu */

/**
 * Implements hook_init().
 */
function custom_wysiwyg_init() {
  drupal_add_css(drupal_get_path('module', 'custom_wysiwyg') . '/css/custom_wysiwyg.css');
}

/**
 * Implements hook_preprocess_page().
 */
function custom_wysiwyg_preprocess_page(&$vars) {
  //dsm($vars['theme_hook_suggestions']);
  if (arg(0) == 'user' and arg(1) == 'files' and !arg(2)) {
    drupal_add_js(drupal_get_path('module', 'custom') . '/js/giaidieu.file.js');
    drupal_add_js(drupal_get_path('module', 'custom_wysiwyg') . '/js/custom_wysiwyg.js');
  }
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function custom_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      return array(
        'custom_wysiwyg_media' => array(
        'path' => drupal_get_path('module', 'custom_wysiwyg') . '/plugins',
        'buttons' => array(
          'custom_wysiwyg_media_button' => t('Giai Điệu Media'),
        ),
        'load' => TRUE,
      ),
    );
    
    break;
  }
}

/**
 * Implements hook_theme().
 */
function custom_wysiwyg_theme($existing, $type, $theme, $path) {
  return array(
    'page__user__files' => array(
      'path' => drupal_get_path('module', 'custom'),
      'template' => 'templates/page--user--files'
    ),
  );
}